export const PAISE_PER_RUPEE = 100n;

export const MINIMUM_AMOUNT_PAISE = 1n;
export const MAXIMUM_AMOUNT_PAISE = 10_000_000n;

export const IDEMPOTENCY_RECORD_LIFETIME_MS = 24 * 60 * 60 * 1_000;

export const SERIALIZABLE_TRANSACTION_MAX_ATTEMPTS = 3;
export const SERIALIZABLE_TRANSACTION_RETRY_DELAY_MS = 25;
